/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CountryData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryData{}

// CountryData struct for CountryData
type CountryData struct {
	// country id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes CountryAttributes `json:"attributes"`
}

type _CountryData CountryData

// NewCountryData instantiates a new CountryData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryData(id string, type_ string, attributes CountryAttributes) *CountryData {
	this := CountryData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCountryDataWithDefaults instantiates a new CountryData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryDataWithDefaults() *CountryData {
	this := CountryData{}
	return &this
}

// GetId returns the Id field value
func (o *CountryData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CountryData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CountryData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CountryData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CountryData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CountryData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CountryData) GetAttributes() CountryAttributes {
	if o == nil {
		var ret CountryAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CountryData) GetAttributesOk() (*CountryAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CountryData) SetAttributes(v CountryAttributes) {
	o.Attributes = v
}

func (o CountryData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CountryData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCountryData := _CountryData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCountryData)

	if err != nil {
		return err
	}

	*o = CountryData(varCountryData)

	return err
}

type NullableCountryData struct {
	value *CountryData
	isSet bool
}

func (v NullableCountryData) Get() *CountryData {
	return v.value
}

func (v *NullableCountryData) Set(val *CountryData) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryData) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryData(val *CountryData) *NullableCountryData {
	return &NullableCountryData{value: val, isSet: true}
}

func (v NullableCountryData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


