/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CountryPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryPolicy{}

// CountryPolicy struct for CountryPolicy
type CountryPolicy struct {
	Data CountryPolicyData `json:"data"`
}

type _CountryPolicy CountryPolicy

// NewCountryPolicy instantiates a new CountryPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryPolicy(data CountryPolicyData) *CountryPolicy {
	this := CountryPolicy{}
	this.Data = data
	return &this
}

// NewCountryPolicyWithDefaults instantiates a new CountryPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryPolicyWithDefaults() *CountryPolicy {
	this := CountryPolicy{}
	return &this
}

// GetData returns the Data field value
func (o *CountryPolicy) GetData() CountryPolicyData {
	if o == nil {
		var ret CountryPolicyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CountryPolicy) GetDataOk() (*CountryPolicyData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CountryPolicy) SetData(v CountryPolicyData) {
	o.Data = v
}

func (o CountryPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CountryPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCountryPolicy := _CountryPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCountryPolicy)

	if err != nil {
		return err
	}

	*o = CountryPolicy(varCountryPolicy)

	return err
}

type NullableCountryPolicy struct {
	value *CountryPolicy
	isSet bool
}

func (v NullableCountryPolicy) Get() *CountryPolicy {
	return v.value
}

func (v *NullableCountryPolicy) Set(val *CountryPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryPolicy(val *CountryPolicy) *NullableCountryPolicy {
	return &NullableCountryPolicy{value: val, isSet: true}
}

func (v NullableCountryPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


