/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CountryPolicyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryPolicyData{}

// CountryPolicyData struct for CountryPolicyData
type CountryPolicyData struct {
	// country id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes CountryPolicyAttributes `json:"attributes"`
}

type _CountryPolicyData CountryPolicyData

// NewCountryPolicyData instantiates a new CountryPolicyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryPolicyData(id string, type_ string, attributes CountryPolicyAttributes) *CountryPolicyData {
	this := CountryPolicyData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCountryPolicyDataWithDefaults instantiates a new CountryPolicyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryPolicyDataWithDefaults() *CountryPolicyData {
	this := CountryPolicyData{}
	return &this
}

// GetId returns the Id field value
func (o *CountryPolicyData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CountryPolicyData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CountryPolicyData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CountryPolicyData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CountryPolicyData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CountryPolicyData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CountryPolicyData) GetAttributes() CountryPolicyAttributes {
	if o == nil {
		var ret CountryPolicyAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CountryPolicyData) GetAttributesOk() (*CountryPolicyAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CountryPolicyData) SetAttributes(v CountryPolicyAttributes) {
	o.Attributes = v
}

func (o CountryPolicyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryPolicyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CountryPolicyData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCountryPolicyData := _CountryPolicyData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCountryPolicyData)

	if err != nil {
		return err
	}

	*o = CountryPolicyData(varCountryPolicyData)

	return err
}

type NullableCountryPolicyData struct {
	value *CountryPolicyData
	isSet bool
}

func (v NullableCountryPolicyData) Get() *CountryPolicyData {
	return v.value
}

func (v *NullableCountryPolicyData) Set(val *CountryPolicyData) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryPolicyData) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryPolicyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryPolicyData(val *CountryPolicyData) *NullableCountryPolicyData {
	return &NullableCountryPolicyData{value: val, isSet: true}
}

func (v NullableCountryPolicyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryPolicyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


