/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCountryStatusDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountryStatusDataAttributes{}

// UpdateCountryStatusDataAttributes struct for UpdateCountryStatusDataAttributes
type UpdateCountryStatusDataAttributes struct {
	// new country status
	Status string `json:"status"`
}

type _UpdateCountryStatusDataAttributes UpdateCountryStatusDataAttributes

// NewUpdateCountryStatusDataAttributes instantiates a new UpdateCountryStatusDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountryStatusDataAttributes(status string) *UpdateCountryStatusDataAttributes {
	this := UpdateCountryStatusDataAttributes{}
	this.Status = status
	return &this
}

// NewUpdateCountryStatusDataAttributesWithDefaults instantiates a new UpdateCountryStatusDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryStatusDataAttributesWithDefaults() *UpdateCountryStatusDataAttributes {
	this := UpdateCountryStatusDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateCountryStatusDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryStatusDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateCountryStatusDataAttributes) SetStatus(v string) {
	o.Status = v
}

func (o UpdateCountryStatusDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountryStatusDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateCountryStatusDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCountryStatusDataAttributes := _UpdateCountryStatusDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCountryStatusDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateCountryStatusDataAttributes(varUpdateCountryStatusDataAttributes)

	return err
}

type NullableUpdateCountryStatusDataAttributes struct {
	value *UpdateCountryStatusDataAttributes
	isSet bool
}

func (v NullableUpdateCountryStatusDataAttributes) Get() *UpdateCountryStatusDataAttributes {
	return v.value
}

func (v *NullableUpdateCountryStatusDataAttributes) Set(val *UpdateCountryStatusDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountryStatusDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountryStatusDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountryStatusDataAttributes(val *UpdateCountryStatusDataAttributes) *NullableUpdateCountryStatusDataAttributes {
	return &NullableUpdateCountryStatusDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCountryStatusDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountryStatusDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


