/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateCountryDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountryDataAttributes{}

// UpdateCountryDataAttributes struct for UpdateCountryDataAttributes
type UpdateCountryDataAttributes struct {
	// city name
	Name *string `json:"name,omitempty"`
}

// NewUpdateCountryDataAttributes instantiates a new UpdateCountryDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountryDataAttributes() *UpdateCountryDataAttributes {
	this := UpdateCountryDataAttributes{}
	return &this
}

// NewUpdateCountryDataAttributesWithDefaults instantiates a new UpdateCountryDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryDataAttributesWithDefaults() *UpdateCountryDataAttributes {
	this := UpdateCountryDataAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCountryDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCountryDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCountryDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCountryDataAttributes) SetName(v string) {
	o.Name = &v
}

func (o UpdateCountryDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountryDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateCountryDataAttributes struct {
	value *UpdateCountryDataAttributes
	isSet bool
}

func (v NullableUpdateCountryDataAttributes) Get() *UpdateCountryDataAttributes {
	return v.value
}

func (v *NullableUpdateCountryDataAttributes) Set(val *UpdateCountryDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountryDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountryDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountryDataAttributes(val *UpdateCountryDataAttributes) *NullableUpdateCountryDataAttributes {
	return &NullableUpdateCountryDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCountryDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountryDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


