/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCountryPolicyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountryPolicyData{}

// UpdateCountryPolicyData struct for UpdateCountryPolicyData
type UpdateCountryPolicyData struct {
	// country id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateCountryPolicyDataAttributes `json:"attributes"`
}

type _UpdateCountryPolicyData UpdateCountryPolicyData

// NewUpdateCountryPolicyData instantiates a new UpdateCountryPolicyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountryPolicyData(id string, type_ string, attributes UpdateCountryPolicyDataAttributes) *UpdateCountryPolicyData {
	this := UpdateCountryPolicyData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCountryPolicyDataWithDefaults instantiates a new UpdateCountryPolicyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryPolicyDataWithDefaults() *UpdateCountryPolicyData {
	this := UpdateCountryPolicyData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCountryPolicyData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryPolicyData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCountryPolicyData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCountryPolicyData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryPolicyData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCountryPolicyData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCountryPolicyData) GetAttributes() UpdateCountryPolicyDataAttributes {
	if o == nil {
		var ret UpdateCountryPolicyDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryPolicyData) GetAttributesOk() (*UpdateCountryPolicyDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCountryPolicyData) SetAttributes(v UpdateCountryPolicyDataAttributes) {
	o.Attributes = v
}

func (o UpdateCountryPolicyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountryPolicyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCountryPolicyData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCountryPolicyData := _UpdateCountryPolicyData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCountryPolicyData)

	if err != nil {
		return err
	}

	*o = UpdateCountryPolicyData(varUpdateCountryPolicyData)

	return err
}

type NullableUpdateCountryPolicyData struct {
	value *UpdateCountryPolicyData
	isSet bool
}

func (v NullableUpdateCountryPolicyData) Get() *UpdateCountryPolicyData {
	return v.value
}

func (v *NullableUpdateCountryPolicyData) Set(val *UpdateCountryPolicyData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountryPolicyData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountryPolicyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountryPolicyData(val *UpdateCountryPolicyData) *NullableUpdateCountryPolicyData {
	return &NullableUpdateCountryPolicyData{value: val, isSet: true}
}

func (v NullableUpdateCountryPolicyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountryPolicyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


