/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCountryData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCountryData{}

// CreateCountryData struct for CreateCountryData
type CreateCountryData struct {
	Type string `json:"type"`
	Attributes CreateCountryDataAttributes `json:"attributes"`
}

type _CreateCountryData CreateCountryData

// NewCreateCountryData instantiates a new CreateCountryData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCountryData(type_ string, attributes CreateCountryDataAttributes) *CreateCountryData {
	this := CreateCountryData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateCountryDataWithDefaults instantiates a new CreateCountryData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCountryDataWithDefaults() *CreateCountryData {
	this := CreateCountryData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateCountryData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateCountryData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateCountryData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateCountryData) GetAttributes() CreateCountryDataAttributes {
	if o == nil {
		var ret CreateCountryDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateCountryData) GetAttributesOk() (*CreateCountryDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateCountryData) SetAttributes(v CreateCountryDataAttributes) {
	o.Attributes = v
}

func (o CreateCountryData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCountryData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateCountryData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCountryData := _CreateCountryData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCountryData)

	if err != nil {
		return err
	}

	*o = CreateCountryData(varCreateCountryData)

	return err
}

type NullableCreateCountryData struct {
	value *CreateCountryData
	isSet bool
}

func (v NullableCreateCountryData) Get() *CreateCountryData {
	return v.value
}

func (v *NullableCreateCountryData) Set(val *CreateCountryData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCountryData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCountryData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCountryData(val *CreateCountryData) *NullableCreateCountryData {
	return &NullableCreateCountryData{value: val, isSet: true}
}

func (v NullableCreateCountryData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCountryData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


