/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCountryDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCountryDataAttributes{}

// CreateCountryDataAttributes struct for CreateCountryDataAttributes
type CreateCountryDataAttributes struct {
	// city name
	Name string `json:"name"`
}

type _CreateCountryDataAttributes CreateCountryDataAttributes

// NewCreateCountryDataAttributes instantiates a new CreateCountryDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCountryDataAttributes(name string) *CreateCountryDataAttributes {
	this := CreateCountryDataAttributes{}
	this.Name = name
	return &this
}

// NewCreateCountryDataAttributesWithDefaults instantiates a new CreateCountryDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCountryDataAttributesWithDefaults() *CreateCountryDataAttributes {
	this := CreateCountryDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCountryDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCountryDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCountryDataAttributes) SetName(v string) {
	o.Name = v
}

func (o CreateCountryDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCountryDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateCountryDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCountryDataAttributes := _CreateCountryDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCountryDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateCountryDataAttributes(varCreateCountryDataAttributes)

	return err
}

type NullableCreateCountryDataAttributes struct {
	value *CreateCountryDataAttributes
	isSet bool
}

func (v NullableCreateCountryDataAttributes) Get() *CreateCountryDataAttributes {
	return v.value
}

func (v *NullableCreateCountryDataAttributes) Set(val *CreateCountryDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCountryDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCountryDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCountryDataAttributes(val *CreateCountryDataAttributes) *NullableCreateCountryDataAttributes {
	return &NullableCreateCountryDataAttributes{value: val, isSet: true}
}

func (v NullableCreateCountryDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCountryDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


