/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCountryPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountryPolicy{}

// UpdateCountryPolicy struct for UpdateCountryPolicy
type UpdateCountryPolicy struct {
	Data UpdateCountryPolicyData `json:"data"`
}

type _UpdateCountryPolicy UpdateCountryPolicy

// NewUpdateCountryPolicy instantiates a new UpdateCountryPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountryPolicy(data UpdateCountryPolicyData) *UpdateCountryPolicy {
	this := UpdateCountryPolicy{}
	this.Data = data
	return &this
}

// NewUpdateCountryPolicyWithDefaults instantiates a new UpdateCountryPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryPolicyWithDefaults() *UpdateCountryPolicy {
	this := UpdateCountryPolicy{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCountryPolicy) GetData() UpdateCountryPolicyData {
	if o == nil {
		var ret UpdateCountryPolicyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryPolicy) GetDataOk() (*UpdateCountryPolicyData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCountryPolicy) SetData(v UpdateCountryPolicyData) {
	o.Data = v
}

func (o UpdateCountryPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountryPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateCountryPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCountryPolicy := _UpdateCountryPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCountryPolicy)

	if err != nil {
		return err
	}

	*o = UpdateCountryPolicy(varUpdateCountryPolicy)

	return err
}

type NullableUpdateCountryPolicy struct {
	value *UpdateCountryPolicy
	isSet bool
}

func (v NullableUpdateCountryPolicy) Get() *UpdateCountryPolicy {
	return v.value
}

func (v *NullableUpdateCountryPolicy) Set(val *UpdateCountryPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountryPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountryPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountryPolicy(val *UpdateCountryPolicy) *NullableUpdateCountryPolicy {
	return &NullableUpdateCountryPolicy{value: val, isSet: true}
}

func (v NullableUpdateCountryPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountryPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


