/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CountriesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountriesCollection{}

// CountriesCollection struct for CountriesCollection
type CountriesCollection struct {
	Data []CountryData `json:"data"`
	Links PaginationData `json:"links"`
}

type _CountriesCollection CountriesCollection

// NewCountriesCollection instantiates a new CountriesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountriesCollection(data []CountryData, links PaginationData) *CountriesCollection {
	this := CountriesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewCountriesCollectionWithDefaults instantiates a new CountriesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountriesCollectionWithDefaults() *CountriesCollection {
	this := CountriesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *CountriesCollection) GetData() []CountryData {
	if o == nil {
		var ret []CountryData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CountriesCollection) GetDataOk() ([]CountryData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CountriesCollection) SetData(v []CountryData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *CountriesCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CountriesCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CountriesCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o CountriesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountriesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CountriesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCountriesCollection := _CountriesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCountriesCollection)

	if err != nil {
		return err
	}

	*o = CountriesCollection(varCountriesCollection)

	return err
}

type NullableCountriesCollection struct {
	value *CountriesCollection
	isSet bool
}

func (v NullableCountriesCollection) Get() *CountriesCollection {
	return v.value
}

func (v *NullableCountriesCollection) Set(val *CountriesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableCountriesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableCountriesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountriesCollection(val *CountriesCollection) *NullableCountriesCollection {
	return &NullableCountriesCollection{value: val, isSet: true}
}

func (v NullableCountriesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountriesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


