/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateCountryStatusData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountryStatusData{}

// UpdateCountryStatusData struct for UpdateCountryStatusData
type UpdateCountryStatusData struct {
	// country id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateCountryStatusDataAttributes `json:"attributes"`
}

type _UpdateCountryStatusData UpdateCountryStatusData

// NewUpdateCountryStatusData instantiates a new UpdateCountryStatusData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountryStatusData(id uuid.UUID, type_ string, attributes UpdateCountryStatusDataAttributes) *UpdateCountryStatusData {
	this := UpdateCountryStatusData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCountryStatusDataWithDefaults instantiates a new UpdateCountryStatusData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryStatusDataWithDefaults() *UpdateCountryStatusData {
	this := UpdateCountryStatusData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCountryStatusData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryStatusData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCountryStatusData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCountryStatusData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryStatusData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCountryStatusData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCountryStatusData) GetAttributes() UpdateCountryStatusDataAttributes {
	if o == nil {
		var ret UpdateCountryStatusDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCountryStatusData) GetAttributesOk() (*UpdateCountryStatusDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCountryStatusData) SetAttributes(v UpdateCountryStatusDataAttributes) {
	o.Attributes = v
}

func (o UpdateCountryStatusData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountryStatusData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCountryStatusData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCountryStatusData := _UpdateCountryStatusData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCountryStatusData)

	if err != nil {
		return err
	}

	*o = UpdateCountryStatusData(varUpdateCountryStatusData)

	return err
}

type NullableUpdateCountryStatusData struct {
	value *UpdateCountryStatusData
	isSet bool
}

func (v NullableUpdateCountryStatusData) Get() *UpdateCountryStatusData {
	return v.value
}

func (v *NullableUpdateCountryStatusData) Set(val *UpdateCountryStatusData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountryStatusData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountryStatusData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountryStatusData(val *UpdateCountryStatusData) *NullableUpdateCountryStatusData {
	return &NullableUpdateCountryStatusData{value: val, isSet: true}
}

func (v NullableUpdateCountryStatusData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountryStatusData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


