/*
countries-svc API

API documentation for countries-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCountry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCountry{}

// UpdateCountry struct for UpdateCountry
type UpdateCountry struct {
	Data UpdateCountryData `json:"data"`
}

type _UpdateCountry UpdateCountry

// NewUpdateCountry instantiates a new UpdateCountry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCountry(data UpdateCountryData) *UpdateCountry {
	this := UpdateCountry{}
	this.Data = data
	return &this
}

// NewUpdateCountryWithDefaults instantiates a new UpdateCountry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCountryWithDefaults() *UpdateCountry {
	this := UpdateCountry{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCountry) GetData() UpdateCountryData {
	if o == nil {
		var ret UpdateCountryData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCountry) GetDataOk() (*UpdateCountryData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCountry) SetData(v UpdateCountryData) {
	o.Data = v
}

func (o UpdateCountry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCountry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateCountry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCountry := _UpdateCountry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCountry)

	if err != nil {
		return err
	}

	*o = UpdateCountry(varUpdateCountry)

	return err
}

type NullableUpdateCountry struct {
	value *UpdateCountry
	isSet bool
}

func (v NullableUpdateCountry) Get() *UpdateCountry {
	return v.value
}

func (v *NullableUpdateCountry) Set(val *UpdateCountry) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCountry(val *UpdateCountry) *NullableUpdateCountry {
	return &NullableUpdateCountry{value: val, isSet: true}
}

func (v NullableUpdateCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


