openapi: 3.1.0
info:
  title: countries-svc API
  description: API documentation for countries-svc
  version: 0.1.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateCountry:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_country
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: city name
    UpdateCountry:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: country id
            type:
              type: string
              enum:
                - update_country
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: city name
    UpdateCountryStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: country id
            type:
              type: string
              enum:
                - update_country_status
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: new country status
    Country:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CountryData'
    CountryData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: country id
        type:
          type: string
          enum:
            - country
        attributes:
          $ref: '#/components/schemas/CountryAttributes'
    CountryAttributes:
      type: object
      required:
        - name
        - status
        - created_at
        - updated_at
      properties:
        name:
          type: string
          description: country name
        status:
          type: string
          enum:
            - active
            - inactive
          description: country status
        created_at:
          type: string
          format: date-time
          description: creation date
        updated_at:
          type: string
          format: date-time
          description: last update date
    CountriesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CountryData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    PaginationData:
      type: object
      required:
        - page_number
        - page_size
        - total_items
      properties:
        page_number:
          type: integer
          format: int64
          description: The current page number.
          example: 1
        page_size:
          type: integer
          format: int64
          description: The number of items per page.
          example: 10
        total_items:
          type: integer
          format: int64
          description: The total number of items available.
          example: 100
