openapi: 3.1.0
info:
  title: countries-svc API
  description: API documentation for countries-svc
  version: 0.1.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    #requests
    CreateCountry:
      $ref: './spec/components/schemas/CreateCountry.yaml'
    UpdateCountry:
      $ref: './spec/components/schemas/UpdateCountry.yaml'
    UpdateCountryStatus:
      $ref: './spec/components/schemas/UpdateCountryStatus.yaml'

    #responses
    Country:
      $ref: './spec/components/schemas/Country.yaml'
    CountryData:
      $ref: './spec/components/schemas/CountryData.yaml'
    CountryAttributes:
      $ref: './spec/components/schemas/CountryAttributes.yaml'
    CountriesCollection:
      $ref: './spec/components/schemas/CountriesCollection.yaml'

    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'